import {
  dokter1,
  dokter2,
  dokter3,
  dokter4,
  pasien1,
  pasien2,
  pasien3,
  pasien4,
} from "../assets";

export const testimonials = [
  {
    id: 1,
    nama: "John",
    penyakit: "Demam Berdarah",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien1}`,
  },
  {
    id: 2,
    nama: "Olivia",
    penyakit: "Batuk Pilek",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien2}`,
  },
  {
    id: 3,
    nama: "Nadia",
    penyakit: "Tipes",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien3}`,
  },
  {
    id: 4,
    nama: "Alex",
    penyakit: "Check-up Rutin",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien4}`,
  },
];

export const doctors = [
  {
    id: 1,
    nama: "Forster Covendon",
    email: "fcovendon0@walmart.com",
    rating: 3,
    gender: "Male",
    harga: 19,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 2,
    nama: "Dorita McKinney",
    email: "dmckinney1@cmu.edu",
    rating: 3,
    gender: "Female",
    harga: 23,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 3,
    nama: "Akim Grassi",
    email: "agrassi2@wikipedia.org",
    rating: 5,
    gender: "Male",
    harga: 40,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 4,
    nama: "Taylor Crinion",
    email: "tcrinion3@java.com",
    rating: 2,
    gender: "Male",
    harga: 49,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 5,
    nama: "Wendy Comerford",
    email: "wcomerford4@51.la",
    rating: 2,
    gender: "Genderfluid",
    harga: 33,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 6,
    nama: "Marianne McElroy",
    email: "mmcelroy5@reverbnation.com",
    rating: 5,
    gender: "Agender",
    harga: 6,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 7,
    nama: "Lay Sculpher",
    email: "lsculpher6@last.fm",
    rating: 5,
    gender: "Male",
    harga: 73,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 8,
    nama: "Phillipe Sallows",
    email: "psallows7@xinhuanet.com",
    rating: 3,
    gender: "Male",
    harga: 12,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 9,
    nama: "Kinny Paolotto",
    email: "kpaolotto8@imageshack.us",
    rating: 1,
    gender: "Male",
    harga: 79,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 10,
    nama: "Coral Kingswood",
    email: "ckingswood9@liveinternet.ru",
    rating: 3,
    gender: "Female",
    harga: 63,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 11,
    nama: "Donnajean Claeskens",
    email: "dclaeskensa@google.es",
    rating: 4,
    gender: "Female",
    harga: 48,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 12,
    nama: "Paddy McCowen",
    email: "pmccowenb@sciencedirect.com",
    rating: 1,
    gender: "Male",
    harga: 67,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 13,
    nama: "Jolyn Beddo",
    email: "jbeddoc@cnet.com",
    rating: 2,
    gender: "Female",
    harga: 28,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 14,
    nama: "Guinevere Goldsbury",
    email: "ggoldsburyd@arstechnica.com",
    rating: 5,
    gender: "Female",
    harga: 72,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 15,
    nama: "Norrie Gentile",
    email: "ngentilee@wikispaces.com",
    rating: 2,
    gender: "Male",
    harga: 5,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 16,
    nama: "Ivy Gon",
    email: "igonf@howstuffworks.com",
    rating: 3,
    gender: "Female",
    harga: 1,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 17,
    nama: "Juanita Arbon",
    email: "jarbong@com.com",
    rating: 3,
    gender: "Female",
    harga: 49,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 18,
    nama: "Cris Naisbitt",
    email: "cnaisbitth@g.co",
    rating: 2,
    gender: "Male",
    harga: 13,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 19,
    nama: "Adelle Kennedy",
    email: "akennedyi@ucsd.edu",
    rating: 3,
    gender: "Bigender",
    harga: 88,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
  {
    id: 20,
    nama: "Rebe Hannibal",
    email: "rhannibalj@friendfeed.com",
    rating: 2,
    gender: "Female",
    harga: 95,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
  },
];
