import {
  dokter1,
  dokter2,
  dokter3,
  dokter4,
  pasien1,
  pasien2,
  pasien3,
  pasien4,
} from "../assets";

export const testimonials = [
  {
    id: 1,
    nama: "John",
    penyakit: "Demam Berdarah",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien1}`,
  },
  {
    id: 2,
    nama: "Olivia",
    penyakit: "Batuk Pilek",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien2}`,
  },
  {
    id: 3,
    nama: "Nadia",
    penyakit: "Tipes",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien3}`,
  },
  {
    id: 4,
    nama: "Alex",
    penyakit: "Check-up Rutin",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien4}`,
  },
];

export const doctors = [
  {
    id: 1,
    nama: "Forster Covendon",
    email: "fcovendon0@walmart.com",
    rating: 3,
    gender: "Laki-laki",
    harga: 19,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Umum",
    deskripsi: "Dokter umum dengan pengalaman dalam berbagai kondisi medis.",
    universitas: "Universitas Kedokteran ABC",
    tahunPengalaman: 8,
  },
  {
    id: 2,
    nama: "Dorita McKinney",
    email: "dmckinney1@cmu.edu",
    rating: 3,
    gender: "Perempuan",
    harga: 23,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Gigi",
    deskripsi: "Spesialisasi dalam perawatan gigi dan masalah mulut.",
    universitas: "Universitas Kedokteran XYZ",
    tahunPengalaman: 10,
  },
  {
    id: 3,
    nama: "Akim Grassi",
    email: "agrassi2@wikipedia.org",
    rating: 5,
    gender: "Laki-laki",
    harga: 40,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Bedah",
    deskripsi: "Ahli dalam operasi dan prosedur bedah.",
    universitas: "Universitas Kedokteran DEF",
    tahunPengalaman: 15,
  },
  {
    id: 4,
    nama: "Taylor Crinion",
    email: "tcrinion3@java.com",
    rating: 2,
    gender: "Laki-laki",
    harga: 49,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Anak",
    deskripsi: "Spesialisasi dalam perawatan kesehatan anak-anak.",
    universitas: "Universitas Kedokteran GHI",
    tahunPengalaman: 6,
  },
  {
    id: 5,
    nama: "Wendy Comerford",
    email: "wcomerford4@51.la",
    rating: 2,
    gender: "Genderfluid",
    harga: 33,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Kandungan",
    deskripsi: "Spesialisasi dalam kesehatan reproduksi wanita.",
    universitas: "Universitas Kedokteran JKL",
    tahunPengalaman: 12,
  },
  {
    id: 6,
    nama: "Marianne McElroy",
    email: "mmcelroy5@reverbnation.com",
    rating: 5,
    gender: "Agender",
    harga: 6,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Jiwa",
    deskripsi: "Ahli dalam perawatan kesehatan mental dan gangguan jiwa.",
    universitas: "Universitas Kedokteran MNO",
    tahunPengalaman: 18,
  },
  {
    id: 7,
    nama: "Lay Sculpher",
    email: "lsculpher6@last.fm",
    rating: 5,
    gender: "Laki-laki",
    harga: 73,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Kulit",
    deskripsi: "Spesialisasi dalam perawatan kulit dan masalah dermatologi.",
    universitas: "Universitas Kedokteran PQR",
    tahunPengalaman: 14,
  },
  {
    id: 8,
    nama: "Phillipe Sallows",
    email: "psallows7@xinhuanet.com",
    rating: 3,
    gender: "Laki-laki",
    harga: 12,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Saraf",
    deskripsi: "Ahli dalam perawatan penyakit saraf dan gangguan neurologi.",
    universitas: "Universitas Kedokteran STU",
    tahunPengalaman: 9,
  },
  {
    id: 9,
    nama: "Kinny Paolotto",
    email: "kpaolotto8@imageshack.us",
    rating: 1,
    gender: "Laki-laki",
    harga: 79,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Mata",
    deskripsi:
      "Spesialisasi dalam perawatan kesehatan mata dan masalah oftalmologi.",
    universitas: "Universitas Kedokteran VWX",
    tahunPengalaman: 5,
  },
  {
    id: 10,
    nama: "Coral Kingswood",
    email: "ckingswood9@liveinternet.ru",
    rating: 3,
    gender: "Perempuan",
    harga: 63,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter THT",
    deskripsi: "Spesialisasi dalam perawatan telinga, hidung, dan tenggorokan.",
    universitas: "Universitas Kedokteran YZ",
    tahunPengalaman: 11,
  },
  {
    id: 11,
    nama: "Donnajean Claeskens",
    email: "dclaeskensa@google.es",
    rating: 4,
    gender: "Perempuan",
    harga: 48,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Jantung",
    deskripsi:
      "Ahli dalam perawatan penyakit jantung dan masalah kardiovaskular.",
    universitas: "Universitas Kedokteran JKLMN",
    tahunPengalaman: 20,
  },
  {
    id: 12,
    nama: "Paddy McCowen",
    email: "pmccowenb@sciencedirect.com",
    rating: 1,
    gender: "Laki-laki",
    harga: 67,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Paru-paru",
    deskripsi:
      "Spesialisasi dalam perawatan penyakit paru-paru dan gangguan pernapasan.",
    universitas: "Universitas Kedokteran XYZ",
    tahunPengalaman: 7,
  },
  {
    id: 13,
    nama: "Jolyn Beddo",
    email: "jbeddoc@cnet.com",
    rating: 2,
    gender: "Perempuan",
    harga: 28,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Ginjal",
    deskripsi: "Ahli dalam perawatan penyakit ginjal dan masalah urologi.",
    universitas: "Universitas Kedokteran ABC",
    tahunPengalaman: 10,
  },
  {
    id: 14,
    nama: "Guinevere Goldsbury",
    email: "ggoldsburyd@arstechnica.com",
    rating: 5,
    gender: "Perempuan",
    harga: 72,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Endokrin",
    deskripsi:
      "Spesialisasi dalam perawatan penyakit endokrin dan masalah hormonal.",
    universitas: "Universitas Kedokteran DEF",
    tahunPengalaman: 16,
  },
  {
    id: 15,
    nama: "Norrie Gentile",
    email: "ngentilee@wikispaces.com",
    rating: 2,
    gender: "Laki-laki",
    harga: 5,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Kulit",
    deskripsi: "Spesialisasi dalam perawatan kulit dan masalah dermatologi.",
    universitas: "Universitas Kedokteran GHI",
    tahunPengalaman: 9,
  },
  {
    id: 16,
    nama: "Ivy Gon",
    email: "igonf@howstuffworks.com",
    rating: 3,
    gender: "Perempuan",
    harga: 1,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Mata",
    deskripsi:
      "Spesialisasi dalam perawatan kesehatan mata dan masalah oftalmologi.",
    universitas: "Universitas Kedokteran JKL",
    tahunPengalaman: 7,
  },
  {
    id: 17,
    nama: "Juanita Arbon",
    email: "jarbong@com.com",
    rating: 3,
    gender: "Perempuan",
    harga: 49,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter THT",
    deskripsi: "Spesialisasi dalam perawatan telinga, hidung, dan tenggorokan.",
    universitas: "Universitas Kedokteran MNO",
    tahunPengalaman: 11,
  },
  {
    id: 18,
    nama: "Cris Naisbitt",
    email: "cnaisbitth@g.co",
    rating: 2,
    gender: "Laki-laki",
    harga: 13,
    photo: `${dokter2}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Jantung",
    deskripsi:
      "Ahli dalam perawatan penyakit jantung dan masalah kardiovaskular.",
    universitas: "Universitas Kedokteran PQR",
    tahunPengalaman: 8,
  },
  {
    id: 19,
    nama: "Adelle Kennedy",
    email: "akennedyi@ucsd.edu",
    rating: 3,
    gender: "Bigender",
    harga: 88,
    photo: `${dokter3}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Jiwa",
    deskripsi: "Ahli dalam perawatan kesehatan mental dan gangguan jiwa.",
    universitas: "Universitas Kedokteran STU",
    tahunPengalaman: 14,
  },
  {
    id: 20,
    nama: "Rebe Hannibal",
    email: "rhannibalj@friendfeed.com",
    rating: 2,
    gender: "Perempuan",
    harga: 95,
    photo: `${dokter4}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Anak",
    deskripsi: "Spesialisasi dalam perawatan kesehatan anak-anak.",
    universitas: "Universitas Kedokteran VWX",
    tahunPengalaman: 6,
  },
];
