import {
  pasien1,
  pasien2,
  pasien3,
  pasien4,
  dokter1,
  dokter2,
  dokter3,
  dokter4,
  dokter5,
  dokter6,
  dokter7,
  dokter8,
  dokter9,
  dokter10,
} from "../assets";
import { Error } from "../pages";

export const testimonials = [
  {
    id: 1,
    nama: "John",
    penyakit: "Demam Berdarah",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien1}`,
  },
  {
    id: 2,
    nama: "Olivia",
    penyakit: "Batuk Pilek",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien2}`,
  },
  {
    id: 3,
    nama: "Nadia",
    penyakit: "Tipes",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien3}`,
  },
  {
    id: 4,
    nama: "Alex",
    penyakit: "Check-up Rutin",
    deskripsi:
      "Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
    foto: `${pasien4}`,
  },
];

export const doctors = [
  {
    id: "price_1NcOjeGGXjd0KQoxCN9NQyVd",
    nama: "Forster Covendon",
    email: "fcovendon0@walmart.com",
    rating: 3,
    gender: "Laki-laki",
    harga: 19,
    photo: `${dokter1}`,
    photos: [`${dokter1}`, `${dokter2}`, `${dokter3}`, `${dokter4}`],
    jenisDokter: "Dokter Umum",
    deskripsi: "Dokter umum dengan pengalaman dalam berbagai kondisi medis.",
    universitas: "Universitas Kedokteran ABC",
    tahunPengalaman: 8,
  },
  {
    id: "price_1NcOl2GGXjd0KQoxDfx5KoJv",
    nama: "Dorita McKinney",
    email: "dmckinney1@cmu.edu",
    rating: 3,
    gender: "Perempuan",
    harga: 23,
    photo: `${dokter2}`,
    photos: [`${dokter2}`, `${dokter3}`, `${dokter4}`, `${dokter5}`],
    jenisDokter: "Dokter Gigi",
    deskripsi: "Spesialisasi dalam perawatan gigi dan masalah mulut.",
    universitas: "Universitas Kedokteran XYZ",
    tahunPengalaman: 10,
  },
  {
    id: "price_1NcOlQGGXjd0KQox3kavYg0U",
    nama: "Akim Grassi",
    email: "agrassi2@wikipedia.org",
    rating: 5,
    gender: "Laki-laki",
    harga: 40,
    photo: `${dokter3}`,
    photos: [`${dokter3}`, `${dokter4}`, `${dokter5}`, `${dokter6}`],
    jenisDokter: "Dokter Bedah",
    deskripsi: "Ahli dalam operasi dan prosedur bedah.",
    universitas: "Universitas Kedokteran DEF",
    tahunPengalaman: 15,
  },
  {
    id: "price_1NcOlgGGXjd0KQoxh5bA4nVc",
    nama: "Taylor Crinion",
    email: "tcrinion3@java.com",
    rating: 2,
    gender: "Laki-laki",
    harga: 49,
    photo: `${dokter4}`,
    photos: [`${dokter4}`, `${dokter5}`, `${dokter6}`, `${dokter7}`],
    jenisDokter: "Dokter Anak",
    deskripsi: "Spesialisasi dalam perawatan kesehatan anak-anak.",
    universitas: "Universitas Kedokteran GHI",
    tahunPengalaman: 6,
  },
  {
    id: "price_1NcOlxGGXjd0KQoxfu2SIIfr",
    nama: "Wendy Comerford",
    email: "wcomerford4@51.la",
    rating: 2,
    gender: "Genderfluid",
    harga: 33,
    photo: `${dokter5}`,
    photos: [`${dokter5}`, `${dokter6}`, `${dokter7}`, `${dokter8}`],
    jenisDokter: "Dokter Kandungan",
    deskripsi: "Spesialisasi dalam kesehatan reproduksi wanita.",
    universitas: "Universitas Kedokteran JKL",
    tahunPengalaman: 12,
  },
  {
    id: "price_1NcOmDGGXjd0KQoxisS5KW72",
    nama: "Marianne McElroy",
    email: "mmcelroy5@reverbnation.com",
    rating: 5,
    gender: "Agender",
    harga: 6,
    photo: `${dokter6}`,
    photos: [`${dokter6}`, `${dokter7}`, `${dokter8}`, `${dokter9}`],
    jenisDokter: "Dokter Jiwa",
    deskripsi: "Ahli dalam perawatan kesehatan mental dan gangguan jiwa.",
    universitas: "Universitas Kedokteran MNO",
    tahunPengalaman: 18,
  },
  {
    id: "price_1NcOmUGGXjd0KQoxuU9nvpET",
    nama: "Lay Sculpher",
    email: "lsculpher6@last.fm",
    rating: 5,
    gender: "Laki-laki",
    harga: 73,
    photo: `${dokter7}`,
    photos: [`${dokter7}`, `${dokter8}`, `${dokter9}`, `${dokter10}`],
    jenisDokter: "Dokter Kulit",
    deskripsi: "Spesialisasi dalam perawatan kulit dan masalah dermatologi.",
    universitas: "Universitas Kedokteran PQR",
    tahunPengalaman: 14,
  },
  {
    id: "price_1NcOmiGGXjd0KQoxqawuDM4o",
    nama: "Phillipe Sallows",
    email: "psallows7@xinhuanet.com",
    rating: 3,
    gender: "Laki-laki",
    harga: 12,
    photo: `${dokter8}`,
    photos: [`${dokter8}`, `${dokter9}`, `${dokter10}`, `${dokter1}`],
    jenisDokter: "Dokter Saraf",
    deskripsi: "Ahli dalam perawatan penyakit saraf dan gangguan neurologi.",
    universitas: "Universitas Kedokteran STU",
    tahunPengalaman: 9,
  },
  {
    id: "price_1NcOmvGGXjd0KQoxVfplz8H2",
    nama: "Kinny Paolotto",
    email: "kpaolotto8@imageshack.us",
    rating: 1,
    gender: "Laki-laki",
    harga: 79,
    photo: `${dokter9}`,
    photos: [`${dokter9}`, `${dokter10}`, `${dokter1}`, `${dokter2}`],
    jenisDokter: "Dokter Mata",
    deskripsi:
      "Spesialisasi dalam perawatan kesehatan mata dan masalah oftalmologi.",
    universitas: "Universitas Kedokteran VWX",
    tahunPengalaman: 5,
  },
  {
    id: "price_1NcOnFGGXjd0KQoxgIBXB50p",
    nama: "Coral Kingswood",
    email: "ckingswood9@liveinternet.ru",
    rating: 3,
    gender: "Perempuan",
    harga: 63,
    photo: `${dokter10}`,
    photos: [`${dokter10}`, `${dokter1}`, `${dokter2}`, `${dokter3}`],
    jenisDokter: "Dokter THT",
    deskripsi: "Spesialisasi dalam perawatan telinga, hidung, dan tenggorokan.",
    universitas: "Universitas Kedokteran YZ",
    tahunPengalaman: 11,
  },
];

export const getDoctorsData = (id) => {
  const dokterData = doctors.find((d) => d.id === parseInt(id));

  return dokterData;
};
